In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [18]:
BASE_DIR = r"data\bronze"

FIANCE_TXN_DB_PATH = r"finance_transactions.csv"
FRAUD_PATTERNS_BDB_PATH = r"fraud_patterns.csv"
MERCHANT_DB_PATH = r"merchant_db.csv"
USER_DB_PATH = r"user_db.csv"

In [19]:
fin_txn_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\finance_transactions.csv")
fraud_pattern_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\fraud_patterns.csv")
merchant_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\merchant_db.csv")
user_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\user_db.csv")

In [21]:
fin_txn_df

,transaction_id,user_id,date,amount,description,merchant_name,location,payment_mode,category
0,TXN0001,U019,11/03/2024,6614.32,Starbucks *Order#99,Starbucks,BBSR,UPI,other
1,TXN0002,U017,2024/01/31,14567.58,Amazon purchase,Amazon,local shop,Cash,refund
2,TXN0003,U007,2024-01-13,12937.22,Local Shop purchase,Local Shop,NaN,UPI,shopping
3,TXN0004,U013,2024-02-13,5755.79,Starbucks !!!,Starbucks,BBSR,Card,shopping
4,TXN0005,U018,2024-01-13,29978.48,Apple purchase,Apple,BBSR,UPI,refund
...,...,...,...,...,...,...,...,...,...
995,TXN0996,U015,2024/02/22,10566.02,Big Bazaar,Big Bazaar,NaN,Card,refund
996,TXN0997,U008,13/03/2024,7355.87,Local Shop *Order#99,Local Shop,NaN,UPI,electronics
997,TXN0998,U011,2024-01-16,12636.47,DMart 0412,DMart,NaN,UPI,refund
998,TXN0999,U006,16-01-2024,22967.63,Starbucks ???,Starbucks,Bhubaneswar,UPI,Food & Beverage
999,TXN1000,U006,10/01/2024,26007.73,Starbucks *Order#99,Starbucks,Bhubaneshwar,UPI,transport

In [22]:
fraud_pattern_df

  pattern_id       merchant amount_range  fraud_flag
0       P001     Big Bazaar        >5000           1
1       P002         Amazon          <50           0
2       P003  Unknown Store          any           1
3       P004       Flipkart       >10000           1
4       P005            OLA        >1000           0
5       P006            NaN       >20000           1

In [23]:
user_df

   user_id income_range          city  spending_limit risk_score
0     U001          NaN   Bhubaneswar         10000.0        low
1     U002      >100000          BBSR         15000.0        0.2
2     U003          NaN           NaN         10000.0       high
3     U004  50000-70000   Bhubaneswar         10000.0        0.5
4     U005      >100000           NaN         50000.0        0.1
5     U006  70000-90000          BBSR             NaN       high
6     U007      >100000       Cuttack         50000.0        low
7     U008  50000-70000          BBSR             NaN       high
8     U009        30000  Bhubaneshwar         15000.0        0.5
9     U010        30000   Bhubaneswar         10000.0       high
10    U011  50000-70000  Bhubaneshwar         20000.0        low
11    U012  50000-70000       Cuttack         50000.0        0.2
12    U013  45000-55000   Bhubaneswar         50000.0        low
13    U014          NaN           NaN         20000.0        0.5
14    U015          NaN   Bhubaneswar         10000.0        0.5
15    U016        30000   Bhubaneswar         15000.0        0.2
16    U017  45000-55000  Bhubaneshwar         25000.0     medium
17    U018      >100000  Bhubaneshwar         20000.0        0.5
18    U019          NaN  Bhubaneshwar             NaN        0.2
19    U020  70000-90000          BBSR         50000.0        0.5
20    U021      >100000       Cuttack         25000.0        low
21    U022          NaN           NaN         15000.0     medium
22    U023  50000-70000          BBSR         10000.0     medium
23    U024  45000-55000  Bhubaneshwar         10000.0        0.5
24    U025  70000-90000  Bhubaneshwar         15000.0        NaN
25    U026  45000-55000       Cuttack         15000.0        low
26    U027      >100000          BBSR             NaN        low
27    U028          NaN           NaN         25000.0       high
28    U029        30000          BBSR         15000.0        NaN
29    U030  50000-70000   Bhubaneswar         10000.0        0.3
30    U031          NaN          BBSR             NaN       high
31    U032  70000-90000   Bhubaneswar         25000.0       high
32    U033  70000-90000       Cuttack         50000.0        low
33    U034  70000-90000   Bhubaneswar             NaN        0.2
34    U035          NaN           NaN         20000.0     medium
35    U036  50000-70000  Bhubaneshwar         25000.0        0.3
36    U037  45000-55000   Bhubaneswar             NaN        low
37    U038  70000-90000          BBSR         50000.0        0.2
38    U039          NaN  Bhubaneshwar             NaN        0.5
39    U040      >100000  Bhubaneshwar         15000.0        0.1
40    U041  70000-90000  Bhubaneshwar         25000.0        0.1
41    U042  50000-70000  Bhubaneshwar         20000.0        0.5
42    U043  50000-70000          BBSR         50000.0        0.2
43    U044  50000-70000       Cuttack         10000.0        0.3
44    U045      >100000       Cuttack         50000.0        0.3
45    U046        30000           NaN         50000.0       high
46    U047      >100000           NaN             NaN        0.5
47    U048          NaN  Bhubaneshwar         25000.0     medium
48    U049  45000-55000           NaN         25000.0        0.2
49    U050      >100000          BBSR         10000.0     medium

In [24]:
merchant_df

,merchant_id,merchant_name,expected_category,avg_transaction_value,risk_level
0,M001,Starbucks,Food & Beverage,300,low
1,M002,Amazon,Shopping,1500,medium
2,M003,Flipkart,E-commerce,1200,medium
3,M004,Big Bazaar,Grocery,800,low
4,M005,OLA,Transport,200,low
5,M006,DMart,Grocery,1000,low
6,M007,Local Shop,NaN,100,high
7,M008,Apple,Electronics,25000,medium
8,M009,Swiggy,Food & Beverage,400,low
9,M010,Unknown Store,???,500,high